language: android
android:
  components:
    - build-tools-23.0.1
    - extra
    - android-23
jdk:
  - oraclejdk8
before_install:
  - export JAVA8_HOME=/usr/lib/jvm/java-8-oracle
  - export JAVA_HOME=$JAVA8_HOME
